# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleHashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('dv', 'Development'), ('ps', 'Personal')], default='dv', max_length=2),
        ),
        migrations.AddField(
            model_name='articlehashtag',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.Article'),
        ),
        migrations.AddField(
            model_name='articlehashtag',
            name='hashtag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.HashTag'),
        ),
    ]
