# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20170301_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlehashtag',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articlehashtag',
            name='hashtag',
        ),
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(to='feed.HashTag'),
        ),
        migrations.DeleteModel(
            name='ArticleHashTag',
        ),
    ]
